tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
              "primary-container": "#6a60ee",
              "inverse-surface": "#2f3034",
              "on-surface-variant": "#474554",
              "primary": "#5144d4",
              "error": "#ba1a1a",
              "secondary-container": "#e2dfde",
              "surface-bright": "#faf9fd",
              "secondary-fixed": "#e5e2e1",
              "on-error": "#ffffff",
              "primary-fixed-dim": "#c4c0ff",
              "error-container": "#ffdad6",
              "on-tertiary-fixed-variant": "#005228",
              "on-primary-fixed-variant": "#3b29be",
              "tertiary-fixed-dim": "#4ae183",
              "tertiary-fixed": "#6bfe9c",
              "surface-container-highest": "#e2e2e6",
              "primary-fixed": "#e3dfff",
              "surface-container-low": "#f4f3f7",
              "surface": "#faf9fd",
              "on-tertiary-fixed": "#00210c",
              "on-error-container": "#93000a",
              "surface-variant": "#e2e2e6",
              "on-secondary": "#ffffff",
              "surface-container": "#eeedf1",
              "inverse-primary": "#c4c0ff",
              "background": "#faf9fd",
              "on-secondary-container": "#636262",
              "tertiary-container": "#008645",
              "outline-variant": "#c8c4d7",
              "secondary-fixed-dim": "#c8c6c5",
              "on-secondary-fixed": "#1b1c1c",
              "on-surface": "#1a1c1f",
              "tertiary": "#006a35",
              "on-tertiary": "#ffffff",
              "on-secondary-fixed-variant": "#474746",
              "surface-tint": "#5447d7",
              "secondary": "#5f5e5e",
              "surface-dim": "#dad9de",
              "on-primary-container": "#fffbff",
              "on-primary-fixed": "#130068",
              "outline": "#777586",
              "on-tertiary-container": "#f6fff4",
              "on-background": "#1a1c1f",
              "on-primary": "#ffffff",
              "inverse-on-surface": "#f1f0f4",
              "surface-container-high": "#e8e8ec",
              "surface-container-lowest": "#ffffff"
      },
      "borderRadius": {
              "DEFAULT": "0.25rem",
              "lg": "0.5rem",
              "xl": "0.75rem",
              "full": "9999px"
      },
      "fontFamily": {
              "headline": ["Inter"],
              "body": ["Inter"],
              "label": ["Inter"]
      }
    },
  },
}
